module.exports = {
    "ranking" : String,
    "name" : String,
    "grade" : String,
    "title" : String,
    "alias" : String,
    "director" :String,
    "actor" : String,
    "length" : String,
    "language" : String,
    "time" : String,
    "genre" : String,
    "country" : String,
    "image" : String,
}